### ISSUE TITLE
Regarding the CPU and the board itself

### ISSUE THREAD

**Issue by AntonKukoba1** [ea/bosch_headunit_root#1]
I believe it's NaviEngine https://elinux.org/NaviEngine
And the CPU was NEC uPD35001

**Comment by ea** [comment]
Oh! That does seem very close, and a number of things match. I'll take a closer look, but it should be useful. Thanks!

**Comment by ea** [comment]
Some internet archeology seems to suggest that NEC released newer versions of NaviEngine 1 , referred to as NaviEngine-mini and NaviEngine-MID, which would match `nemid` references that can be found in the system. Any useful details about it seem to be lost to attrition, though. I'll update the docs with a bit more info about them.

**Comment by rempeldev** [comment]
https://www.nec.com/en/global/techrep/journal/g07/n04/pdf/070409.pdf

**Comment by ea** [comment]
Thanks for the tips! Updated the system overview to point to NaviEngine.
