### ISSUE TITLE
Start a wiki or make additional docs?

### ISSUE THREAD

**Issue by ea** [ea/bosch_headunit_root#16]
Trying to decide if it would be easier to just start a wiki to document reversing progress , or just create new markdown docs in existing repo... 
Github wiki's are technically just another repository so we'd have to deal with pull requests there too. Leaning towards just keeping everything in this repository as majority of it is just writeups and documents anyway.

**Comment by raburton** [comment]
I'd assumed the wiki was simpler, but sounds like it'd be easier to keep it in the main repo then.

**Comment by ea** [comment]
in the repository it is.
