### ISSUE TITLE
infiniti q50

### ISSUE THREAD

**Issue by Injineers** [ea/bosch_headunit_root#2]
Hey Nice work.

I myself have a 2016 Q50, my unit looks a bit different but I am going to try this & i will report back.

great work

**Comment by rempeldev** [comment]
The head units can look a bit different on the outside, but if you see any other manufacturer than Bosch, this wont work. We have 3 different head unit manufacturers at Nissan. You may have a Clarion unit in your Q50 being that its a 3.7L luxury car. Its actually marketed as the V37 Skyline in japan. I'll have to crack open FAST tomorrow and see what part number those have.

**Comment by Injineers** [comment]
I actually have the 3.0 TT version in the states here, but interior is the same across all.

I havent tried it yet, but will this weekend.

**Comment by rempeldev** [comment]
So according to my look up, you should be a clarion unit. It's a 3 piece system with the GPS unit and display being seperate from the head unit. Main head unit should be part # 28330-4HB4A, the GPS unit should be 25915-4HB4D, and the screen or DCU should be part number 28387-4HK2C. So I wouldn't attempt this particular jailbreak on your Q50. I used US 2016 Infiniti Q50 with VR30DDTT engine for the lookup.

**Comment by ea** [comment]
Yea, by the looks of it, it's a completely different platform.

**Comment by rempeldev** [comment]
When I have some extra time I will try to provide an expanded list of vehicles that should contain these headunits for Nissan and Infiniti.

**Comment by rempeldev** [comment]
2014 Xterra S model has a Panasonic head unit - not compatible
2020 Titan has Bosch unit, but new design with NXP processor - not compatible

**Comment by rempeldev** [comment]
2019-2020 Frontier Pro4x and SL contain the proper head units - compatible

**Comment by ea** [comment]
Thanks @rempeldev , i'll keep that in mind. I'm closing this issue.

**Comment by uBadRequest** [comment]
So sorry to comment on an old closed issue, but I have same car @Eno423!  The Infiniti infotainment system sucks :(

I found something you guys might find interesting.

Infiniti InTouch Android source code
https://github.com/RyanFu/java_lib/tree/0745c6704e9bd34c51f5bb62810bed192d057896/Hap2

Source code for Bosch headunit apps?
https://github.com/RyanFu/java_lib/blob/0745c6704e9bd34c51f5bb62810bed192d057896/bosch_hmiapps.zip

There some other interesting stuff in this guys repository too.

I hope someone can leverage this information :)
