### ISSUE TITLE
Confirm operation in my Bosh

### ISSUE THREAD

**Issue by robustini** [ea/bosch_headunit_root#29]
Just to confirm the operation, at the moment only testing, in the unit mounted on my 2018 Nissan X-Trail T32 (EU).
Software: F106, Hardware: 034.
This is the content of it_worked:

Linux (none) 2.6.34.13-02254-g839a100 #1 SMP PREEMPT Tue Nov 24 15:35:26 IST 2015 armv6l GNU/Linux

So I suppose the transition to the real root phase should work.
But even more interesting will be the possibility, for example, to implement features that are currently not endured, for example, reading audio files in FLAC format, support for extFAT and many other things.
Two years have already passed since this hack, but I don't see anyone developing anything, but I remain hopeful.
It would obviously take some good souls to get their hands on it.
Thanks!

**Comment by ea** [comment]
That's awesome. Thanks for letting me know. I've updated the confirmed working doc. That's a new FW version I haven't seen before. 
Hope you have fun exploring the system!

**Comment by robustini** [comment]
![Senza titolo](https://github.com/ea/bosch_headunit_root/assets/3864712/31f7e1c2-050a-4a76-ac34-782fd55ded7d)
