### ISSUE TITLE
Script confirmed working for 2014 Rogue

### ISSUE THREAD

**Issue by genericjim** [ea/bosch_headunit_root#4]
2014 Rogue - USA
Software: D407
Hardware: 031

rootfs script appears to work and writes it_worked file to usb drive. I am currently waiting for a network adapter to test further. 

it_worked:
Linux (none) 2.6.34.13-02022-g0e24498 #1 SMP PREEMPT Wed Aug 6 08:56:05 IST 2014 armv6l GNU/Linux

**Comment by ea** [comment]
Thanks for letting me know! 

That's a slightly newer firmware version, good to know it's still the same. I'll start a list of confirmed models.
