### ISSUE TITLE
USB device enumeration question

### ISSUE THREAD

**Issue by shtry** [ea/bosch_headunit_root#6]
Hi.

Thanks for sharing the good content!

What hardware did you use when testing the Umap2 tool?

Maybe, FaceDancer21(https://int3.cc/products/facedancer21)?  

I use the "GreatFET One" tool, but that command doesn't work.

**Comment by ea** [comment]
Yes, I've used Facedancer21 board as i already had it lying around. GreatFET  should be able to function and do the same things as facedanced, though I'm not sure if it would require any changes to Umap2.

**Comment by ea** [comment]
I took a closer look and saw your questions on umap2 issue tracker too. Unlike GoodFET or original Facedancer, greatfet doesn't directly expose UART device such as /dev/ttyUSB0 or anything, but uses libusb in a more direct manner so it will require some changes to Umap2 to make it work.

**Comment by shtry** [comment]
Hi. @ea 

I will look at it with your answer.

Thank you for being so helpful!
